services:
  postgres:
    image: postgres:16.4-alpine
    container_name: iyzico_saas_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: iyzico_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54323:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
